### ISSUE TITLE
The link and image popup closes automatically on the inline preset.

### ISSUE THREAD

**Issue by Fedeorlandau** [xdan/jodit#582] opened 2020-12-17 15:35 UTC
**Jodit Version:**  latest

**Browser:**  All
**OS:**  All
**Is React App:**  False

**Code**

https://xdsoft.net/jodit/play.html?preset=inline

**Expected behavior:**
When you click the link button it should open the link modal and when you click on the input for adding the link it should keep the modal open
**Actual behavior:**
The modal closes as soon as you tap on the input

![bug](https://user-images.githubusercontent.com/10283686/102508832-9e334700-4064-11eb-8bb6-338a6a4241e5.gif)

Update: a mouseup event is causing this. I debugged it and removed all the mouseup events and the popover doesn't close anymore on typing on the input.

Maybe here? https://github.com/xdan/jodit/blob/25f0b49837e42d9ca52569c37e477dafe87d668f/src/plugins/inline-popup/inline-popup.ts#L184

**Comment by xdan** [comment] 2020-12-18 21:54
Duplicate of #515

**Closed as completed** 2020-12-20 14:24 UTC
Labels: bug, duplicate
