### ISSUE TITLE
Full Screen showing elements not part of editable content

### ISSUE THREAD

**Issue by crlzfaiz** [xdan/jodit#763] opened 2021-12-21 09:47 UTC
**Jodit Version:**  3.4.xxx

**Browser:**  Chrome
**OS:**  Windows
**Is React App:** False

**Code**

```js
// Refer to https://xdsoft.net/jodit/
```

**Expected behavior:**
Full screen showing only editor area
**Actual behavior:**
In full screen mode, Jodit editor is showing elements that are not part of editable content
![image](https://user-images.githubusercontent.com/32922908/146908542-08853a0b-95b0-489c-988e-61fa306a9e7c.png)

**Comment by xdan** [comment] 2022-01-05 15:37
Duplicate of #753

**Closed as completed by xdan** 2022-01-05 15:37 UTC
Labels: bug, bug-in-doc
