### ISSUE TITLE
Non focusable input in dialog

### ISSUE THREAD

**Issue by spaceexperiment** [xdan/jodit#883] opened 2022-08-30 10:16 UTC
**Jodit Version:**  3.19.3

**Browser:**  Chrome
**OS:**  Mac
**Is React App:**  True

It's not possible to enter text in the input field to insert links when the 
editor itself is rendered in popup (mui dialog in this case, https://mui.com/material-ui/react-dialog/#main-content).
I can do all other operations in the dialog (clicking check boxes). but not enter text in the input to modify the link name and url.

<img width="511" alt="Screen Shot 2022-08-30 at 13 10 44" src="https://user-images.githubusercontent.com/2048846/187411867-a8daff5c-df2d-4c28-8823-3dc14f55b541.png">

**Comment by xdan** [comment] 2022-09-04 10:36
Duplicate of #879

**Closed as completed by xdan** 2022-09-04 10:36 UTC

**Comment by jpfluger** [comment] 2023-01-10 02:31
As an FYI for bootstrap 5.2.3, flipping the configurable `focus` option to `false` solved the problem of the Modal dialog overriding Jodit input events. [Reference](https://getbootstrap.com/docs/5.2/components/modal/#options). It didn't matter or not if `tabindex` was used.
