### ISSUE TITLE
Text alignment is highlighted several times in Toolbar

### ISSUE THREAD

**Issue by Pestichen** [xdan/jodit#325] opened 2020-01-21 13:02 UTC
**Jodit Version:**  3.2.16

**Browser:**  Chrome/IE/Safari/Firefox
**OS:**  Only Windows tested

Hi guys, 
ill think i may have just discovered a bug.
![JoditBug](https://user-images.githubusercontent.com/681027/72806950-93a2de80-3c56-11ea-89c5-264d9d464b9f.gif)
To reproduce:
1. Create any table.
2. Give some cells some text justification.
3. Give that table itself (see .gif above) a text alignment.
4. Please have a look at the toolbar and see that it has several orientations on one selection.

![JoditBug1](https://user-images.githubusercontent.com/681027/72806956-9998bf80-3c56-11ea-81c4-78e949c47e35.png)

```js
// A *self-contained* demonstration of the problem follows...
```

**Expected behavior:**

Of course, only the current selection would be expected (i.e. the display of the current selection).

**Actual behavior:**

Text alignment is highlighted several times in Toolbar

**Comment by xdan** [comment] 2020-02-10 21:49
Duplicate of #239

**Closed as completed** 2020-02-12 23:07 UTC
Labels: bug, WIP
