### ISSUE TITLE
<style> tag wrapping problem

### ISSUE THREAD

**Issue by EdgarIsaiSC** [xdan/jodit#754] opened 2021-11-23 19:33 UTC
**Jodit Version:**  3.9.6

**Browser:**  Chrome/FF/Opera
**OS:**  Linux
**Is React App:** True

**Expected behavior:**
Using the style tag should not be affected when using WYSIWYG

**Actual behavior:**
When I use `<style>` tag then WYSIWYG wraps it in `<p>` tag

same problem as in https://github.com/xdan/jodit/issues/620

**Comment by xdan** [comment] 2022-01-05 15:37
Duplicate of #620

**Closed as completed** 2022-03-27 19:16 UTC
Labels: bug, need an error repetition algorithm
