### ISSUE TITLE
Playground broken on tab Buttons

### ISSUE THREAD

**Issue by helvenk** [xdan/jodit#604] opened 2021-01-18 07:49 UTC
https://xdsoft.net/jodit/play.html?currentTab=Buttons

Could you please fix it as soon, I need this to know how to set the buttons.

![image](https://user-images.githubusercontent.com/20789074/104886319-8113d000-59a4-11eb-9b33-0aec93541424.png)

**Comment by xdan** [comment] 2021-01-19 13:08
Duplicate of #602

**Closed as completed** 2021-04-27 08:03 UTC
