### ISSUE TITLE
it is not ok

### ISSUE THREAD

**Issue by suqiuhui** [xdan/jodit#481] opened 2020-08-17 10:17 UTC
**Jodit Version:**  3.4.15

**Browser:**  
**OS:**  

![image](https://user-images.githubusercontent.com/19644289/90385800-340a9580-e0b6-11ea-9fa4-310c2616a24f.png)

i am sorry for both of these questions, they don't work in my code, The version I'm using is 3.4.15

**Expected behavior:**

**Actual behavior:**

**Comment by xdan** [comment] 2020-09-01 22:00
![image](https://user-images.githubusercontent.com/794318/91910438-b353b800-ecb7-11ea-90c1-c3b03b369aab.png)

Added  option in playground https://xdsoft.net/jodit/play.html?useSearch=false
How is it working in your case?

**Comment by xdan** [comment] 2020-09-01 22:01
Duplicate of #408
Duplicate of #407

**Closed as completed** 2021-03-07 20:46 UTC
Labels: need an error repetition algorithm, Need more information
