### ISSUE TITLE
IE11: copy-paste of text-html content always pastes content on top of the editor

### ISSUE THREAD

**Issue by corrrso** [xdan/jodit#460] opened 2020-08-05 09:04 UTC
**Jodit Version:**  3.4.17

**Browser:**  Internet Explorer 11
**OS:**  Windows 10

Hi again. On Internet Explorer 11, everything I copy-paste is inserted at the top of the editor. I also tried to enable askBeforePasteFromWord and AskBeforePasteHTML, but no luck.
Images are copied in the right place instead.

![2020-08-05 10-52-52_Trim](https://user-images.githubusercontent.com/23524581/89393648-6528b480-d70b-11ea-8afd-7b8af0030e72.gif)

**Comment by xdan** [comment] 2020-08-05 15:38
Duplicate of #340

**Closed as completed by xdan** 2020-08-05 15:38 UTC
