### ISSUE TITLE
single toolbar for many editable area

### ISSUE THREAD

**Issue by romarioliveira25** [xdan/jodit#258] opened 2019-09-18 13:27 UTC
**Jodit Version:**  3.2.46

**Question**
Has any way to use a single toolbar to control many editable areas?
Like this question: https://stackoverflow.com/questions/57465949/can-i-edit-multiple-textareas-and-div-elements-with-a-single-jodit-toolbar-like

**Comment by romarioliveira25** [comment] 2019-12-26 15:00
hello?

**Comment by xdan** [comment] 2020-01-19 10:40
Duplicate of #244 
Added in https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#3314

**Closed as completed by xdan** 2020-01-19 10:40 UTC
