### ISSUE TITLE
In source code view <!DOCTYPE html>, <html>, <body> is not getting saved

### ISSUE THREAD

**Issue by eldhosejoys** [xdan/jodit#241] opened 2019-08-12 16:42 UTC
In the source code view when we type `<!DOCTYPE html>`  and `<html>` on the top of the code and try to save it. It doesn't get saved. Even when I switch over to 'source' and 'editor' view the `<!DOCTYPE html>` is disappearing. 

All these elements `<!DOCTYPE html>` , `<html>` , `<body>` gets disappear in codeview. Watch this video `https://youtu.be/7T-7W5aOyqc`

If you get this fixed. Please reply me.

**Comment by c5racing** [comment] 2019-10-23 13:19
Is there any update to this?  We would really like to use the Jodit Editor; however, with the html, head, body, and other tags being removed, we're limited.

**Comment by eldhosejoys** [comment] 2019-10-23 16:40
> With the html, head, body, and other tags being removed, we're limited.

Soo true

**Comment by xdan** [comment] 2020-01-12 19:24
Duplicate of #174

**Closed as completed** 2020-01-16 18:43 UTC
Labels: Feature Request

**Comment by xdan** [comment] 2020-01-16 18:49
Hi, https://github.com/xdan/jodit/blob/master/CHANGELOG.MD#feature
